const SUCCESS = "1000";
const ERROR = "2000";
const ENTIRY_EXIST = "3000";
const ENTITY_NOT_EXIST = "4000";
const ERROR_ID_EXIST = "5000";
const ERROR_Name_EXIST = "6000";
const ERROR_PHONE_EXIST = "7000";
const PHONENUMBER_EXIST = "8000";
const WRONG_PASSWORD = "10000";
const UNAUTHORIZATION = "11000";


module.exports = { PHONENUMBER_EXIST,ENTITY_NOT_EXIST, WRONG_PASSWORD, UNAUTHORIZATION, SUCCESS, ENTIRY_EXIST, ERROR, ERROR_ID_EXIST,ERROR_Name_EXIST,ERROR_PHONE_EXIST };