const ENTITY_NOT_EXIST = "4000";
const ENTIRY_EXIST = "5000";
const WRONG_PASSWORD = "2000";
const UNAUTHORIZATION = "3000";
const SUCCESS = "1000";
const ERROR = "5000";

module.exports = { ENTITY_NOT_EXIST, WRONG_PASSWORD, UNAUTHORIZATION, SUCCESS, ENTIRY_EXIST, ERROR };